# other-service
server:
  port: 8088
spring:
  mvc:
    cors:
      enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      config:
        username: nacos  # 需要同时配置config的认证
        password: nacos
  application:
    name: other-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/CareCenter?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      maximum-pool-size: 17
      minimum-idle: 8
      servlet:
        multipart:
          max-file-size: 5MB
          max-request-size: 20MB
      mail:
        host: smtp.qq.com
        port: 465
        username: 844439287@qq.com
        password: ygdqwhplngmxbegc
        properties:
          mail:
            smtp:
              ssl:
                enable: true
      data:
        redis:
          port: 6379
          host: 127.0.0.1
mybatis-plus:
  type-aliases-package: com.edu.common.entity
logging:
  level:
    com.edu.checkin: debug
minio:
  config:
    endpoint: http://127.0.0.1:9000
    username: admin
    password: 123456
knife4j:
  enable: true
filter:
  white:
    urls:
      - /user/add
      - /user/change
      - /user/login
      - /user/check
      - /api/sendcode
      - /api/verifycode
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs
      - /webjars/**
dashscope:
  api:
    key: sk-ee83b6a7922840019fa88682f0961553